//! Debian/apt coexistence: DPkg hooks call hidden `oil` subcommands so `apt install`
//! can skip packages already managed in Oil's Cellar.

use crate::error::{OilError, Result};
use crate::install::InstallState;
use crate::system_pm::SystemPm;
use crate::ui::dirs;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command as StdCommand;

const HOOKS_DIR: &str = "/etc/apt/apt.conf.d";
const HOOK_FILE: &str = "99oil-dpkg-hooks";
const WRAPPER_NAME: &str = "oil-apt-preinstall";

pub fn apt_preinstall_check_packages(package_names: &[String]) -> Result<()> {
    if package_names.is_empty() {
        return Ok(());
    }

    let rt = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .map_err(|e| OilError::InstallError(format!("runtime: {e}")))?;

    rt.block_on(async {
        let state = InstallState::new()?;
        state.sync_from_cellar().await.ok();
        let installed = state.load().await?;
        let mut blocked = Vec::new();
        for name in package_names {
            if oil_has_formula(name, &installed) {
                blocked.push(name.clone());
            }
        }
        if blocked.is_empty() {
            return Ok(());
        }
        for pkg in &blocked {
            eprintln!(
                "oil: refusing apt install of '{}' — already installed via oil Cellar (remove with: oil uninstall {})",
                pkg, pkg
            );
        }
        Err(OilError::InstallError(
            "apt install blocked for oil-managed package(s)".into(),
        ))
    })
}

fn oil_has_formula(
    dpkg_name: &str,
    installed: &std::collections::HashMap<String, crate::install::InstalledPackage>,
) -> bool {
    if installed.contains_key(dpkg_name) {
        return true;
    }
    installed.keys().any(|k| k.eq_ignore_ascii_case(dpkg_name))
}

fn oil_binary_for_hooks() -> Result<PathBuf> {
    if let Ok(p) = std::env::var("OIL_APT_HOOK_BIN") {
        let path = PathBuf::from(p);
        if path.is_file() {
            return Ok(path);
        }
    }
    let self_exe = std::env::current_exe()
        .map_err(|e| OilError::InstallError(format!("current_exe: {e}")))?;
    if self_exe.is_file() {
        return Ok(self_exe);
    }
    Err(OilError::InstallError(
        "cannot resolve oil binary for apt hooks".into(),
    ))
}

fn hook_wrapper_script(oil_bin: &Path) -> String {
    let oil = shell_escape(oil_bin);
    format!(
        r#"#!/bin/sh
# Generated by oil apt-hooks install — do not edit.
set -eu
OIL_BIN={oil}
for deb in "$@"; do
  [ -f "$deb" ] || continue
  pkg="$(dpkg-deb -f "$deb" Package 2>/dev/null || true)"
  [ -n "$pkg" ] || continue
  "$OIL_BIN" __apt-preinstall --pkg "$pkg" || exit 1
done
exit 0
"#
    )
}

fn apt_conf_fragment(wrapper: &Path) -> String {
    format!(
        "// Managed by oil (oil apt-hooks install). Prevents apt from installing over oil Cellar packages.\nDPkg::Pre-Install-Pkgs {{ \"{wrapper}\"; }};\n",
        wrapper = shell_escape(wrapper)
    )
}

fn shell_escape(path: &Path) -> String {
    let s = path.to_string_lossy();
    if s.chars().all(|c| c.is_ascii_alphanumeric() || "/._-+:=".contains(c)) {
        s.into_owned()
    } else {
        format!("'{}'", s.replace('\'', "'\\''"))
    }
}

pub fn install_apt_hooks() -> Result<()> {
    if !cfg!(target_os = "linux") {
        return Err(OilError::PlatformNotSupported(
            "apt hooks are only supported on Linux".into(),
        ));
    }
    let rt = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .map_err(|e| OilError::InstallError(format!("runtime: {e}")))?;
    let pm = rt.block_on(SystemPm::detect());
    if pm.as_ref() != Some(&SystemPm::Apt) {
        return Err(OilError::PlatformNotSupported(
            "apt hooks require a Debian/Ubuntu-style host (apt)".into(),
        ));
    }

    let oil_bin = oil_binary_for_hooks()?;
    let oil_dir = dirs::oil_dir()?;
    fs::create_dir_all(&oil_dir)?;

    let wrapper_path = oil_dir.join(WRAPPER_NAME);
    fs::write(&wrapper_path, hook_wrapper_script(&oil_bin))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(&wrapper_path, fs::Permissions::from_mode(0o755))?;
    }

    let conf_path = PathBuf::from(HOOKS_DIR).join(HOOK_FILE);
    if !Path::new(HOOKS_DIR).exists() {
        return Err(OilError::InstallError(format!(
            "{} does not exist (are you root on a Debian system?)",
            HOOKS_DIR
        )));
    }

    let conf = apt_conf_fragment(&wrapper_path);
    if nix::unistd::geteuid().is_root() {
        fs::write(&conf_path, &conf)?;
    } else {
        let tmp = oil_dir.join(HOOK_FILE);
        fs::write(&tmp, &conf)?;
        let status = StdCommand::new("sudo")
            .args(["cp", tmp.to_str().unwrap_or(""), conf_path.to_str().unwrap_or("")])
            .status()
            .map_err(|e| OilError::InstallError(format!("sudo: {e}")))?;
        if !status.success() {
            return Err(OilError::InstallError(
                "failed to install apt hook config (sudo cp)".into(),
            ));
        }
        let _ = fs::remove_file(&tmp);
    }

    println!("Installed apt hook: {}", conf_path.display());
    println!("Wrapper: {}", wrapper_path.display());
    Ok(())
}

pub fn remove_apt_hooks() -> Result<()> {
    let conf_path = PathBuf::from(HOOKS_DIR).join(HOOK_FILE);
    let wrapper_path = dirs::oil_dir()?.join(WRAPPER_NAME);

    if conf_path.exists() {
        if nix::unistd::geteuid().is_root() {
            fs::remove_file(&conf_path)?;
        } else {
            let status = StdCommand::new("sudo")
                .args(["rm", "-f", conf_path.to_str().unwrap_or("")])
                .status()
                .map_err(|e| OilError::InstallError(format!("sudo: {e}")))?;
            if !status.success() {
                return Err(OilError::InstallError("failed to remove apt hook config".into()));
            }
        }
    }
    if wrapper_path.exists() {
        let _ = fs::remove_file(&wrapper_path);
    }
    println!("Removed oil apt hooks (if present)");
    Ok(())
}

pub fn apt_hooks_status() -> Result<()> {
    let conf_path = PathBuf::from(HOOKS_DIR).join(HOOK_FILE);
    let wrapper_path = dirs::oil_dir()?.join(WRAPPER_NAME);
    if conf_path.is_file() && wrapper_path.is_file() {
        println!("apt hooks: installed");
        println!("  {}", conf_path.display());
        println!("  {}", wrapper_path.display());
    } else {
        println!("apt hooks: not installed (run: oil apt-hooks install)");
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn apt_conf_quotes_wrapper_path() {
        let conf = apt_conf_fragment(Path::new("/home/u/.oil/oil-apt-preinstall"));
        assert!(conf.contains("DPkg::Pre-Install-Pkgs"));
        assert!(conf.contains("oil-apt-preinstall"));
    }
}